# Generated by Django 5.2.15 on 2026-07-02 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(default=0.0)),
                ('duration_watched', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='courses.coursenode')),
            ],
            options={
                'verbose_name_plural': 'watch histories',
                'ordering': ['-last_watched_at'],
            },
        ),
    ]
