# Generated by Django 5.2.15 on 2026-07-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_updated_at_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.coursenode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
