# Generated by Django 5.2.15 on 2026-07-02 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('root_path', models.CharField(max_length=1024)),
                ('cover_image', models.ImageField(blank=True, upload_to='covers/courses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CourseNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relative_path', models.CharField(max_length=1024)),
                ('node_type', models.CharField(choices=[('directory', 'Directory'), ('file', 'File')], max_length=16)),
                ('file_type', models.CharField(blank=True, choices=[('video', 'Video'), ('audio', 'Audio'), ('subtitle', 'Subtitle'), ('document', 'Document'), ('image', 'Image'), ('archive', 'Archive'), ('source_code', 'Source Code'), ('other', 'Other')], default='', max_length=20)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='courses.course')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.coursenode')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('course', 'relative_path')},
            },
        ),
    ]
