# Generated by Django 5.1.6 on 2026-07-01 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relative_path', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'relative_path')},
            },
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relative_path', models.CharField(max_length=1024)),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('subtitle', 'Subtitle'), ('document', 'Document'), ('image', 'Image'), ('archive', 'Archive'), ('source_code', 'Source Code'), ('other', 'Other')], max_length=20)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.course')),
            ],
            options={
                'ordering': ['relative_path'],
                'unique_together': {('course', 'relative_path')},
            },
        ),
    ]
