# Generated by Django 5.2.15 on 2026-07-02 15:29

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=apps.courses.models._cover_upload_path),
        ),
    ]
