# Generated by Django 5.2.15 on 2026-07-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_updated_at_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
