# Generated by Django 5.2.15 on 2026-07-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='remaining_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='total_duration',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='watched_duration',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
