# Generated by Django 5.1.6 on 2026-07-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=1024, unique=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('codec', models.CharField(blank=True, default='', max_length=50)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bitrate', models.IntegerField(blank=True, null=True)),
                ('file_format', models.CharField(blank=True, default='', max_length=50)),
                ('subtitle_paths', models.JSONField(blank=True, default=list)),
                ('extracted_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'media metadata',
            },
        ),
    ]
