# Generated by Django 5.2.15 on 2026-07-02 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(blank=True, null=True)),
                ('codec', models.CharField(blank=True, default='', max_length=50)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bitrate', models.IntegerField(blank=True, null=True)),
                ('file_format', models.CharField(blank=True, default='', max_length=50)),
                ('subtitle_paths', models.JSONField(blank=True, default=list)),
                ('extracted_at', models.DateTimeField(auto_now=True)),
                ('course_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_metadata', to='courses.coursenode')),
            ],
            options={
                'verbose_name_plural': 'media metadata',
            },
        ),
    ]
